import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import ExerciseContextProvider from "@/context/ExerciseContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ExerciseContextProvider>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#15171D",
                color: "#FFFFFF",
                border: "1px solid #2D313B",
              },
              success: {
                iconTheme: {
                  primary: "#CCFF00",
                  secondary: "#000000",
                },
              },
            }}
          />
          <Navbar></Navbar>
          <main className="pt-18">{children}</main>
          <Footer></Footer>
        </ExerciseContextProvider>
      </body>
    </html>
  );
}
